export const profession = [
  'خياط',
  'بدون',
  'مياوم',
  'تاجر',
  'مستخدم',
  'آخر',
  'كهربائي',
  'عامل',
  'حارس',
  'خباز',
  'بحري',
  'حلاق',
  'صباغ',
  'نادل',
  'صاحب مقهى',
  'بحار',
  'سائق',
  'خراز',
  'شاوش',
  'فلاح',
  'بناء',
  'مساعد تاجر',
  'نجار',
  'نجار',
  'جباس',
  'متقاعد',
  'ميكانيكي السيارات',
  'إسكافي',
  'بقال',
  'بائع متجول',
  'لحام بالكهرباء أو بالغاز',
  'جزار',
  'رصاص',
  'مهن أخرى',
  'عاطل',
  'مطال',
  'بستاني',
  'ربة بيت',
  'طالب',
  'مصور',
  'تلميذ',
  'صانع تقليدي',
  'ميكانيكي الدراجات',
  'حداد',
  'مساعد سائق',
  'مهاجر',
  'موظف',
  'أجير',
  'قهوجي',
  'شغالة',
  'بائع خضر',
  'كاتب',
  'حوات',
  'كساب',
  'مساعد جزار',
  'فندقي',
  'عطار',
  'صياد السمك',
  'طباخ',
  'مصلح دراجات',
  'كسال',
  'فراش',
  'عشاب',
  'مساعد بناء',
  'زليجي',
  'نقاش',
  'صائغ',
  'صاحب ضيعة',
  'بائع الدجاج',
  'تاجر بالخارج',
  'كناش',
  'صحافي',
  'مساعد كهربائي',
  'إسفنجي',
  'تاجر جملة',
  'طرازة',
]

export const regles = [
  { id: "RG1", value: "Consommation d'électricité par tranche de consommation de téléphone" },
  { id: "RG2", value: "Consommation de téléphone par tranche de consommation d'électricité" },
  { id: "RG3", value: "Frais logement par nombre de chambres" },
  { id: "RG4", value: "Consommation d'eau selon le nombre de chambres" },
  { id: "RG5", value: "Consommation d'életrictié par type de logement" },
  { id: "RG6", value: "Consommation de téléphone par rapport au frais logement" },
  { id: "RG6_Bis", value: "Consommation de téléphone par rapport au type logement" },
  { id: "RG7", value: "Consommation d'électricité par rapport au nombre de chambres" },
  { id: "RG8", value: "Consommation d'eau par rapport à la Taille du Menage" },
  { id: "RG9", value: "Consommation de téléphone par rapport à la Taille du Menage" },
  { id: "RG10", value: "Consommation d'électricité par rapport à la Taille du Menage" },
  { id: "RG11", value: "Frais logement par rapport à la  Taille du Menage" },
  { id: "RG12", value: "Depense totale selon la Taille du Menage" },
  { id: "RG13", value: "Depense totale selon le nombre de chambres" },
  { id: "RG14", value: "Depense totale selon la fonction" },
  { id: "RG15", value: "Frais logement par rapport à la région" },
  { id: "RG16", value: "Consommation d'eau par rapport à la région" },
]

export const profession_fr = [
  'Tailleur',
  'Sans travail',
  'Compagnon',
  'Marchande',
  'Employeur',
  'Autre',
  'Electrique',
  'Ouvrier',
  'Gardien',
  'Boulanger',
  'Nautique',
  'Coiffeur',
  'Teinturier',
  'Garçon',
  'Propriétaire du café',
  'Un marin',
  'Conducteur',
  'perles',
  'Chawsh',
  'Agriculteur',
  'Imeuble',
  'Assistant concessionnaire',
  'Charpentier',
  'Charpentier',
  'Gabbas',
  'Retraité ',
  'Mécanicien automobile',
  'Cordonnier',
  'Épicier',
  'Colporteur',
  'Soudage électrique ou au gaz',
  'Boucher',
  'Balles',
  'Autres métiers',
  'Sans emploi',
  'Prolongé',
  'Jardinier',
  'Femme au foyer',
  'Etudiant',
  'Photographe',
  'Un élève',
  'Fabricant traditionnel',
  'Mécanicien vélo',
  'Forgeron',
  'Assistant chauffeur',
  'Immigrant',
  'Officier',
  'Employé',
  'Café',
  'Travail',
  'Vendeur de légumes',
  'Écrivain',
  'Baleines',
  'Kasab',
  'Assistant boucher',
  'Hotel',
  'Attar',
  'Pêcheur',
  'Cuisinier',
  'Réparateur de vélos',
  'Paresseux',
  'Le matelas',
  'Herbe',
  'Assistant bâtiment',
  'Zéligi',
  'نقاش',
  'Bijoutier',
  'Manoir',
  'Proprétaire de poulet',
  'Commercant à l\'étranger',
  'Canache',
  'Journaliste',
  'Assistant électricien',
  'Spongieux',
  'Grossiste',
  'Style',
]
